backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

locale: "ru"

collections:
  - name: "stories"
    label: "Истории"
    format: "json"
    extension: "json"
    editor: { preview: false }
    files:
      - file: "data/stories.json"
        label: "Лента историй"
        name: "stories_file"
        fields:
          - label: "Истории"
            name: "stories"
            widget: "list"
            fields:
              - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
              - {label: "Заголовок", name: "title", widget: "string"}
              - {label: "Текст", name: "text", widget: "text"}
              - {label: "Теги", name: "tags", widget: "list", required: false}
              - label: "Картинки"
                name: "images"
                widget: "list"
                required: false
                field: {label: "Файл", name: "image", widget: "image"}
              - {label: "Настроение", name: "mood", widget: "string", required: false}
